# Generated by Django 4.1.1 on 2022-10-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=122)),
                ('Desc', models.CharField(max_length=1022)),
            ],
        ),
    ]
